[node]
detect-drivers = false
[[node.driver-configuration]]
display-name = "Chrome"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"107.0.5304.87\", \"platformName\": \"linux\", \"goog:chromeOptions\": {\"binary\": \"/opt/google/chrome/google-chrome\"}}"
webdriver-executable = '/opt/selenium/chromedriver-107.0.5304.62'
